# Generated by Django 5.0.4 on 2025-05-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_cart_cartitem_userprofile_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
    ]
