# Generated by Django 5.0.4 on 2025-05-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_userprofile_is_seller_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
