# Generated by Django 4.2 on 2025-05-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_remove_cartitem_cart_delete_cart_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
