services:
  product_api:
    build: ./product_service
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./product_service:/code
      - ./data/media:/code/media
      - ./product_service/.env:/code/.env
    ports:
      - "3341:8888"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=cn334Admin
      - POSTGRES_PASSWORD=cn334Admin
      - POSTGRES_HOST=db
  frontend:
    build: ./app_frontend
    volumes:
      - ./app_frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3341
    depends_on:
      - product_api
