services:
  product_api:
    build: ./product_service
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./product_service:/code
      - ./data/media:/code/media
      - ./product_service/.env:/code/.env
    ports:
      - "3344:8888"
    environment:
      - DATABASE_URL=postgresql://reudb_user:pMXsddDmVLVKRkeNnDVjchdydwVSxnR3@dpg-d0did56uk2gs73d5ar5g-a.singapore-postgres.render.com/reudb
  frontend:
    build: ./app_frontend
    command: npm run dev
    volumes:
      - ./app_frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3344
    depends_on:
      - product_api
