# Generated by Django 4.2.13 on 2025-05-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CLOTHING', 'Clothing'), ('ACCESSORIES', 'Accessories'), ('BOOKS', 'Books'), ('ELECTRONICS', 'Electronics'), ('SPORT_EQUIPMENT', 'Sport Equipment'), ('STATIONARY_ART', 'Stationary & Art Supplies'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
