# Generated by Django 5.1.7 on 2025-05-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_service', '0004_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
