# Generated by Django 4.2.13 on 2025-05-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_management', '0002_user_faculty_user_postcode_user_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
    ]
