# Generated by Django 4.2 on 2025-05-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0009_remove_cartitem_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
